[pack]
namespace = "pro"
name      = "coder"
version   = "0.3.3-WIP"

# -- Optional section
license  = "MIT or Apache 2"
homepage = "https://aipack.ai/"
repo     = "https://github.com/aipack-ai/packs-pro"
author   = "Jeremy Chone"

